name: multiscroll_pagination_builder
description: "Multiscroll pagination builder"

version: 1.0.0
homepage: https://github.com/rn7cvj/multiscroll_pagination_builder.git

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3

  # Model serialization
  freezed_annotation: ^3.1.0

  # Localizations
  # intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.6.0
  freezed: ^3.2.0

  flutter_lints: ^5.0.0
